### ISSUE TITLE
Ch02 - Preprocessing - 'preprocess_expanded' function does not take the global end date but the individual 'ts' max_date

### ISSUE THREAD

**Issue by nisargvp** [PacktPublishing/Modern-Time-Series-Forecasting-with-Python#9]
see line[32] in 02 - Preprocessing London Smart Meter Dataset. Does that need a modification?

**Comment by manujosephv** [comment]
Can you post the line here? not able to find the numbered line you are referring to?

**Comment by nisargvp** [comment]
Yeah here it is,  for the expanded form you are using x['day'].max() instead of max_date:

 dr = pd.date_range(start=x['day'].min(), end=x['day'].max(), freq="1D")

Also, the pre-processing steps make sense but for some reason, experimenting with block_1: for compact form, I was not able to find any NaNs despite some of the LCLids having an earlier end_date and altho the expanded form has NaNs, they are in its LCLid and not missing values for existing LCLids (do we need a ffill here?)

**Comment by manujosephv** [comment]
I guess this line is from the expanded form function. It is x['day'].max() itself, because intention there is to insert NaNs only in between start and end of each time series..  If a timeseries last value is before `max_date`, we are not adding NaN from that date to `max_date`.

And in compact form, there wouldn't be NaNs because the entire timeseries is stored as a list in a cell of the dataframe.. the NaN would be inside the list.

**Comment by nisargvp** [comment]
I see, that makes sense. It raises one more question from me though - why are adding NaN from end of time series to max_date for the compact form preparation. Also, you might need to make a some update to the book to the expanded form function explanation (you mention - "2. Create a standard DataFrame using the start date and the global end date." instead of x['day'].max

Thanks for your time. Really appreciate it!

**Comment by manujosephv** [comment]
closing the issue
